// <auto-generated />
namespace Project_X_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedEmbarks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedEmbarks));
        
        string IMigrationMetadata.Id
        {
            get { return "201708111927118_updatedEmbarks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
